### ISSUE TITLE
Idea: Large-scale centralised IFF functions

### ISSUE THREAD

**Issue by WaferMouse** [WaferMouse/edmc-chatviewer#2]
A semi-automated IFF solution using in-game chat seems like a noble endeavor.  Some kind of out-of-channel authentication would likely be involved.

**Comment by inorton** [comment]
I have been thinking the exact same thing! This would be great, perhaps backed up by a web-of-trust type thing.

**Comment by inorton** [comment]
I have started an identity system in https://github.com/inorton/NULLTeamPlugin

**Comment by WaferMouse** [comment]
@inorton I was starting to look at something like a Tox bot or something, kinda like a federated network.  Thinking something like sending a /ping on in-game chat to trigger clients in the same instance.  Will have a look at what you've got started, maybe we could sync up on this.

**Comment by WaferMouse** [comment]
@inorton That being said, my throttle just went **kaput**.  So I'm probably out of the actual game for at least a while.

**Comment by WaferMouse** [comment]
Closing as it seems that FDev have something planned for next year.
