### ISSUE TITLE
Chatviewer is partially impaired since Elite Dangerous patch 2.4

### ISSUE THREAD

**Issue by ArchangelaDanzig** [WaferMouse/edmc-chatviewer#4]
Since Elite Dangerous 2.4, chatviewer will show my outbound chat but not inbound chat from direct, local, or wing messages.

**Comment by WaferMouse** [comment]
@ArchangelaDanzig Thanks for reporting this, I haven't had much cause to use the plugin myself since 2.4.  I've added an untested fix, feel free to give it a crack, I'll test it myself next chance I get.  Closing for the moment at least.

**Comment by ArchangelaDanzig** [comment]
I'm happy to report that the plug-in works again after your update, for local, direct, and wing chats. Incoming as well as outgoing is working wonderfully. Thank you so much!
